# Site settings
baseurl = "/"
languageCode = "cn"
title = "疫战2020"
theme = "hugo-theme-cactus-plus"

googleAnalytics = "UA-140829719-3"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

[params]
	author = "疫战2020"
	description = "Site Description"
	bio = "新型冠状病毒疫情智能应答语料库"

	twitter = "your_twitter_id"
	facebook = "your_facebook_id"

	enableRSS = false
	enableToc = true

	enableDisqus = false
	disqusShortname = "your_disqus_short_name"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = ["static/css/article.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""

	[params.Links]


# Add additional social link entries underneath
[social]
	# facebook-square = "https://www.facebook.com/nodejh"
	# twitter-square = "https://www.twitter.com/nodejh"
	github-square = "https://github.com/yizhan2020"
